package com.timearchive.configuration

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(PayPalPaymentProperties::class)
class ConfigurationPropertiesConfiguration
